id: P009159
initial_creation_type: ocr
source_metadata:
  id: bdr:W1
  title: གངས་ཅན་གསོ་རིག་རྒྱ་མཚོའི་འཇུག་ངོགས
  author: ''
  volumes:
    b642e992281142699dc2c552fe52f9ee:
      image_group_id: I1PD340
      title: ''
      volume_number: 1
      total_pages: 350
